### ISSUE TITLE
iRobot Create 1 Support

### ISSUE THREAD

**Issue by Guofeng-Tang** [tork-a/roomblock#8]
I am using iRobot Create 1 this time, but the driver doesn't seem to support Create 1 very well, seems like it is a known issue that Create 1 odometry is very unusable. (https://github.com/AutonomyLab/create_autonomy/issues/41, https://answers.ros.org/question/31935/createroomba-odometry/)

Create 1 can actually handle hector mapping very well, but not amcl navigation without the proper odom messages, is there a way to solve this problem? Thanks in advance.

**Comment by 7675t** [comment]
This package uses [create_node](http://wiki.ros.org/create_node), not [create_autonomy](http://wiki.ros.org/create_autonomy) for controlling Roomba. Plese check [the launch file](https://github.com/tork-a/roomblock/blob/master/roomblock_bringup/launch/include/real_roomba.launch.xml#L3).

And yes, iRobot create and Roomba produce bad odometry. I think that's why [turtlebot_node.py calculate the odometry by itself.](https://github.com/turtlebot/turtlebot_create/blob/indigo/create_node/nodes/turtlebot_node.py#L443)
 
Though I'm not sure about Create (I don't have it), if your Create publish correct /joint_states, I think this code should work well also for Create.

**Comment by stephen-tang** [comment]
Thanks for your reply, I have been trying to use hector_mapping to provide the odom as it's quite accurate and stable in mapping, now the problem is I am not sure how to configure the tf, can you show me yours when doing amcl navigation?

**Comment by mzahana** [comment]
@stephen-tang I am facing issues with `odom` on iRobot Create 1. Have you found a solution. Have you found a solution to the odom problem?

**Comment by Guofeng-Tang** [comment]
No, I have not.
